title: "Duong Le — Systems Engineer"
description: "VMware/vSphere, Windows/AD, Security Systems, Cisco Networking, Odoo+POS, AI/RAG, Observability"

# Project site settings
url: "https://dle2022.github.io"
baseurl: "/portfolio"

# Use Cayman (remote theme). Do NOT keep a `theme:` line.
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
