# _config.yml
title: "Duong Le — Systems Engineer"
description: "VMware/vSphere, Windows Serverws, Security Systems, Network Security, Cloud AWS, Azure, Windows/AD, Networking (CCNA), Odoo + POS, AI/RAG, Observability"
url: "https://dle2022.github.io/portfolio"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme   # required for remote themes
  - jekyll-seo-tag        # metadata for search/social
  - jekyll-sitemap        # /sitemap.xml

# Optional: Google Analytics
# google_analytics: G-XXXXXXXXXX
