title: "Duong Le — Systems Engineer"
description: "vSphere/ESXi, Windows/AD, Networking (CCNA), Odoo+POS integrations, AI/RAG, Observability."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
baseurl: "/portfolio"   # <-- add this
